name: Update Pools Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Запуск каждые 30 минут
  workflow_dispatch:  # Возможность запускать вручную

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest pools data
        run: curl -s "https://yields.llama.fi/pools" -o pools.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add pools.json
          git commit -m "Auto-update pools data" || exit 0
          git push
